import { 
  Employee, 
  Department, 
  AttendanceRecord, 
  LeaveRequest, 
  LeaveBalance, 
  TaskItem, 
  PerformanceReview, 
  PayrollRecord, 
  DocumentItem, 
  Holiday, 
  Announcement, 
  NotificationItem, 
  AuditLog, 
  CompanySettings 
} from '../types';

// Wings Corporation: Exclusively 2 Departments (HR and Sales)
export const initialDepartments: Department[] = [
  { 
    id: 'dept-1', 
    name: 'HR', 
    code: 'HR', 
    managerId: 'emp-1', 
    description: 'Human Resources, employee lifecycle, biometric attendance, talent acquisition, payroll, and staff welfare', 
    isActive: true, 
    createdAt: '2024-01-01' 
  },
  { 
    id: 'dept-2', 
    name: 'Sales', 
    code: 'SALES', 
    managerId: 'emp-11', 
    description: 'Corporate B2B enterprise sales, retail merchant onboarding, client acquisitions, and business development', 
    isActive: true, 
    createdAt: '2024-01-01' 
  },
];

// Exact 39 Employees provided by Wings Corporation: Exclusively Sales & HR, Zero profile picture URLs
export const initialEmployees: Employee[] = [
  {
    id: 'emp-1',
    employeeCode: 'WC-001',
    firstName: 'Varsha',
    lastName: '',
    fullName: 'Varsha',
    avatarUrl: '',
    dateOfBirth: '1995-04-12',
    gender: 'Female',
    personalEmail: 'varsha@wings-marketing.in',
    workEmail: 'varsha@wings-marketing.in',
    phone: '+91 9230628055',
    mobileNumber: '9230628055',
    reportingTo: 'Harshita',
    companyRole: 'Manager',
    expiryDate: '21-10-2026',
    emergencyContact: { name: 'Family Contact', relationship: 'Family', phone: '+91 9230628050' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-1',
    designation: 'HR Manager',
    joiningDate: '2023-10-21',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 15000,
      hra: 6000,
      allowances: 7000,
      incentives: 2000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Varsha',
      accountNumber: '918230628055',
      bankName: 'HDFC Bank',
      ifscCode: 'HDFC0001245',
      panNumber: 'ABCDE1234F',
      branchName: 'Park Street, Kolkata'
    },
    documents: [
      { id: 'doc-emp1-1', title: 'Aadhaar Card', category: 'Identity', fileName: 'aadhaar_varsha.pdf', fileUrl: '#', uploadDate: '2023-10-21', verified: true }
    ]
  },
  {
    id: 'emp-2',
    employeeCode: 'WC-002',
    firstName: 'Tamaghna',
    lastName: '',
    fullName: 'Tamaghna',
    avatarUrl: '',
    dateOfBirth: '1998-08-19',
    gender: 'Male',
    personalEmail: 'tamaghna@wings-marketing.in',
    workEmail: 'tamaghna@wings-marketing.in',
    phone: '+91 7003998195',
    mobileNumber: '7003998195',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '21-10-2026',
    emergencyContact: { name: 'Guardian', relationship: 'Family', phone: '+91 7003998100' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2023-10-21',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Tamaghna',
      accountNumber: '700399819501',
      bankName: 'State Bank of India',
      ifscCode: 'SBIN0000456',
      panNumber: 'FGHIJ5678K',
      branchName: 'Salt Lake, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-3',
    employeeCode: 'WC-003',
    firstName: 'Sujal',
    lastName: '',
    fullName: 'Sujal',
    avatarUrl: '',
    dateOfBirth: '1996-03-14',
    gender: 'Male',
    personalEmail: 'sujal@wings-marketing.in',
    workEmail: 'sujal@wings-marketing.in',
    phone: '+91 9230628058',
    mobileNumber: '9230628058',
    reportingTo: 'Sakshi Jaiswal',
    companyRole: 'Manager',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Emergency Family', relationship: 'Family', phone: '+91 9230628000' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Manager',
    joiningDate: '2024-07-24',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 15000,
      hra: 6000,
      allowances: 7000,
      incentives: 2000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Sujal',
      accountNumber: '923062805801',
      bankName: 'ICICI Bank',
      ifscCode: 'ICIC0000987',
      panNumber: 'KLMNO9012P',
      branchName: 'Bhowanipore, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-4',
    employeeCode: 'WC-004',
    firstName: 'Subhasish',
    lastName: 'Bose',
    fullName: 'Subhasish Bose',
    avatarUrl: '',
    dateOfBirth: '1997-11-05',
    gender: 'Male',
    personalEmail: 'subhasish.bose@wings-marketing.in',
    workEmail: 'subhasish.bose@wings-marketing.in',
    phone: '+91 9230521850',
    mobileNumber: '9230521850',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Family Contact', relationship: 'Parent', phone: '+91 9230521800' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2024-07-24',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Subhasish Bose',
      accountNumber: '923052185001',
      bankName: 'Axis Bank',
      ifscCode: 'UTIB0001122',
      panNumber: 'QRSTU3456V',
      branchName: 'Gariahat, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-5',
    employeeCode: 'WC-005',
    firstName: 'Souvik',
    lastName: 'Mitra',
    fullName: 'Souvik Mitra',
    avatarUrl: '',
    dateOfBirth: '1999-01-22',
    gender: 'Male',
    personalEmail: 'souvik.mitra@wings-marketing.in',
    workEmail: 'souvik.mitra@wings-marketing.in',
    phone: '+91 9230354682',
    mobileNumber: '9230354682',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '21-10-2026',
    emergencyContact: { name: 'Family', relationship: 'Brother', phone: '+91 9230354600' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2023-10-21',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Souvik Mitra',
      accountNumber: '923035468201',
      bankName: 'HDFC Bank',
      ifscCode: 'HDFC0002345',
      panNumber: 'WXYZA7890B',
      branchName: 'Ruby, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-6',
    employeeCode: 'WC-006',
    firstName: 'Souvik',
    lastName: 'Bhattacharya',
    fullName: 'Souvik Bhattacharya',
    avatarUrl: '',
    dateOfBirth: '1998-05-18',
    gender: 'Male',
    personalEmail: 'souvik.b@wings-marketing.in',
    workEmail: 'souvik.b@wings-marketing.in',
    phone: '+91 9230189534',
    mobileNumber: '9230189534',
    reportingTo: 'Sujal',
    companyRole: 'Executive',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Family Contact', relationship: 'Parent', phone: '+91 9230189500' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2024-07-24',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Souvik Bhattacharya',
      accountNumber: '923018953401',
      bankName: 'Kotak Mahindra Bank',
      ifscCode: 'KKBK0004567',
      panNumber: 'CDEFG1234H',
      branchName: 'New Town, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-7',
    employeeCode: 'WC-007',
    firstName: 'Sourav',
    lastName: 'Roy',
    fullName: 'Sourav Roy',
    avatarUrl: '',
    dateOfBirth: '1997-09-30',
    gender: 'Male',
    personalEmail: 'sourav.roy@wings-marketing.in',
    workEmail: 'sourav.roy@wings-marketing.in',
    phone: '+91 9230621918',
    mobileNumber: '9230621918',
    reportingTo: 'Varsha',
    companyRole: 'Executive',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Family', relationship: 'Father', phone: '+91 9230621900' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-1',
    designation: 'HR Executive',
    joiningDate: '2024-07-24',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Sourav Roy',
      accountNumber: '923062191801',
      bankName: 'State Bank of India',
      ifscCode: 'SBIN0001289',
      panNumber: 'IJKLM5678N',
      branchName: 'Behala, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-8',
    employeeCode: 'WC-008',
    firstName: 'Sourashis',
    lastName: 'Chanda',
    fullName: 'Sourashis Chanda',
    avatarUrl: '',
    dateOfBirth: '1998-12-11',
    gender: 'Male',
    personalEmail: 'sourashis@wings-marketing.in',
    workEmail: 'sourashis@wings-marketing.in',
    phone: '+91 9230554215',
    mobileNumber: '9230554215',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '21-10-2026',
    emergencyContact: { name: 'Family', relationship: 'Parent', phone: '+91 9230554200' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2023-10-21',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Sourashis Chanda',
      accountNumber: '923055421501',
      bankName: 'HDFC Bank',
      ifscCode: 'HDFC0001980',
      panNumber: 'OPQRS9012T',
      branchName: 'Alipore, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-9',
    employeeCode: 'WC-009',
    firstName: 'Shreya',
    lastName: 'Sasmal',
    fullName: 'Shreya Sasmal',
    avatarUrl: '',
    dateOfBirth: '2000-02-14',
    gender: 'Female',
    personalEmail: 'shreya.sasmal@wings-marketing.in',
    workEmail: 'shreya.sasmal@wings-marketing.in',
    phone: '+91 9230195320',
    mobileNumber: '9230195320',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Family Contact', relationship: 'Mother', phone: '+91 9230195300' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2024-07-24',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Shreya Sasmal',
      accountNumber: '923019532001',
      bankName: 'ICICI Bank',
      ifscCode: 'ICIC0003412',
      panNumber: 'UVWXY3456Z',
      branchName: 'Jadavpur, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-10',
    employeeCode: 'WC-010',
    firstName: 'Sayan',
    lastName: 'Shaw',
    fullName: 'Sayan Shaw',
    avatarUrl: '',
    dateOfBirth: '1998-07-04',
    gender: 'Male',
    personalEmail: 'sayan.shaw@wings-marketing.in',
    workEmail: 'sayan.shaw@wings-marketing.in',
    phone: '+91 9230346010',
    mobileNumber: '9230346010',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '21-10-2026',
    emergencyContact: { name: 'Family', relationship: 'Father', phone: '+91 9230346000' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2023-10-21',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Sayan Shaw',
      accountNumber: '923034601001',
      bankName: 'Bank of Baroda',
      ifscCode: 'BARB0KOLKAT',
      panNumber: 'ABCDE7890F',
      branchName: 'Dum Dum, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-11',
    employeeCode: 'WC-011',
    firstName: 'Sakshi',
    lastName: 'Jaiswal',
    fullName: 'Sakshi Jaiswal',
    avatarUrl: '',
    dateOfBirth: '1996-09-03',
    gender: 'Female',
    personalEmail: 'sakshijais0309@gmail.com',
    workEmail: 'sakshijais0309@gmail.com',
    phone: '+91 9230651453',
    mobileNumber: '9230651453',
    reportingTo: 'Harshita',
    companyRole: 'Manager',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Family Contact', relationship: 'Family', phone: '+91 9230651400' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Manager',
    joiningDate: '2024-07-24',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 15000,
      hra: 6000,
      allowances: 7000,
      incentives: 2000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Sakshi Jaiswal',
      accountNumber: '923065145301',
      bankName: 'HDFC Bank',
      ifscCode: 'HDFC0000156',
      panNumber: 'GHIJK1234L',
      branchName: 'Salt Lake Sector 5, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-12',
    employeeCode: 'WC-012',
    firstName: 'Ronodip',
    lastName: 'Sill',
    fullName: 'Ronodip Sill',
    avatarUrl: '',
    dateOfBirth: '1995-10-15',
    gender: 'Male',
    personalEmail: 'ronodipsill00@gmail.com',
    workEmail: 'ronodipsill00@gmail.com',
    phone: '+91 9230651452',
    mobileNumber: '9230651452',
    reportingTo: 'Ardhendu',
    companyRole: 'Manager',
    expiryDate: '21-10-2026',
    emergencyContact: { name: 'Family', relationship: 'Parent', phone: '+91 9230651400' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Manager',
    joiningDate: '2023-10-21',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 15000,
      hra: 6000,
      allowances: 7000,
      incentives: 2000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Ronodip Sill',
      accountNumber: '923065145201',
      bankName: 'ICICI Bank',
      ifscCode: 'ICIC0000234',
      panNumber: 'MNOPQ5678R',
      branchName: 'Camac Street, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-13',
    employeeCode: 'WC-013',
    firstName: 'Rajib',
    lastName: 'Singh',
    fullName: 'Rajib Singh',
    avatarUrl: '',
    dateOfBirth: '1997-04-18',
    gender: 'Male',
    personalEmail: 'rajib.singh@wings-marketing.in',
    workEmail: 'rajib.singh@wings-marketing.in',
    phone: '+91 9230521854',
    mobileNumber: '9230521854',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '21-10-2026',
    emergencyContact: { name: 'Family', relationship: 'Brother', phone: '+91 9230521800' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2023-10-21',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Rajib Singh',
      accountNumber: '923052185401',
      bankName: 'Axis Bank',
      ifscCode: 'UTIB0002345',
      panNumber: 'STUVW9012X',
      branchName: 'Howrah, West Bengal'
    },
    documents: []
  },
  {
    id: 'emp-14',
    employeeCode: 'WC-014',
    firstName: 'Rahul',
    lastName: 'Roy',
    fullName: 'Rahul Roy',
    avatarUrl: '',
    dateOfBirth: '1999-06-25',
    gender: 'Male',
    personalEmail: 'rahul.roy@wings-marketing.in',
    workEmail: 'rahul.roy@wings-marketing.in',
    phone: '+91 9230189530',
    mobileNumber: '9230189530',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '21-10-2026',
    emergencyContact: { name: 'Family Contact', relationship: 'Parent', phone: '+91 9230189500' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2023-10-21',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Rahul Roy',
      accountNumber: '923018953001',
      bankName: 'HDFC Bank',
      ifscCode: 'HDFC0000789',
      panNumber: 'YZABC3456D',
      branchName: 'Tollygunge, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-15',
    employeeCode: 'WC-015',
    firstName: 'Prosenjeet',
    lastName: 'Mahato',
    fullName: 'Prosenjeet Mahato',
    avatarUrl: '',
    dateOfBirth: '1998-03-12',
    gender: 'Male',
    personalEmail: 'prosenjeet.m@wings-marketing.in',
    workEmail: 'prosenjeet.m@wings-marketing.in',
    phone: '+91 9230628056',
    mobileNumber: '9230628056',
    reportingTo: 'Sakshi Jaiswal',
    companyRole: 'Executive',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Family', relationship: 'Father', phone: '+91 9230628000' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2024-07-24',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Prosenjeet Mahato',
      accountNumber: '923062805601',
      bankName: 'State Bank of India',
      ifscCode: 'SBIN0002345',
      panNumber: 'EFGHI7890J',
      branchName: 'Rajarhat, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-16',
    employeeCode: 'WC-016',
    firstName: 'Priyam',
    lastName: 'Dhar',
    fullName: 'Priyam Dhar',
    avatarUrl: '',
    dateOfBirth: '1994-08-20',
    gender: 'Male',
    personalEmail: 'priyam.dhar@wings-marketing.in',
    workEmail: 'priyam.dhar@wings-marketing.in',
    phone: '+91 9903861280',
    mobileNumber: '9903861280',
    reportingTo: 'Harshita',
    companyRole: 'Manager',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Family Contact', relationship: 'Spouse', phone: '+91 9903861200' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-1',
    designation: 'HR Manager',
    joiningDate: '2024-07-24',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 15000,
      hra: 6000,
      allowances: 7000,
      incentives: 2000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Priyam Dhar',
      accountNumber: '990386128001',
      bankName: 'HDFC Bank',
      ifscCode: 'HDFC0000456',
      panNumber: 'KLMNO1234P',
      branchName: 'Southern Avenue, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-17',
    employeeCode: 'WC-017',
    firstName: 'Md',
    lastName: 'Iqbal',
    fullName: 'Md Iqbal',
    avatarUrl: '',
    dateOfBirth: '1997-02-17',
    gender: 'Male',
    personalEmail: 'md.iqbal@wings-marketing.in',
    workEmail: 'md.iqbal@wings-marketing.in',
    phone: '+91 9230354689',
    mobileNumber: '9230354689',
    reportingTo: 'Sakshi Jaiswal',
    companyRole: 'Executive',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Family', relationship: 'Brother', phone: '+91 9230354600' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2024-07-24',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Md Iqbal',
      accountNumber: '923035468901',
      bankName: 'Axis Bank',
      ifscCode: 'UTIB0001567',
      panNumber: 'QRSTU5678V',
      branchName: 'Park Circus, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-18',
    employeeCode: 'WC-018',
    firstName: 'MD Arshad',
    lastName: 'Javed',
    fullName: 'MD Arshad Javed',
    avatarUrl: '',
    dateOfBirth: '1998-09-14',
    gender: 'Male',
    personalEmail: 'arshad.javed@wings-marketing.in',
    workEmail: 'arshad.javed@wings-marketing.in',
    phone: '+91 9230521853',
    mobileNumber: '9230521853',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '21-10-2026',
    emergencyContact: { name: 'Family', relationship: 'Parent', phone: '+91 9230521800' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2023-10-21',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'MD Arshad Javed',
      accountNumber: '923052185301',
      bankName: 'Kotak Mahindra Bank',
      ifscCode: 'KKBK0001234',
      panNumber: 'WXYZA9012B',
      branchName: 'Ripon Street, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-19',
    employeeCode: 'WC-019',
    firstName: 'Manish',
    lastName: 'Kumar',
    fullName: 'Manish Kumar',
    avatarUrl: '',
    dateOfBirth: '1997-12-08',
    gender: 'Male',
    personalEmail: 'manish.k@wings-marketing.in',
    workEmail: 'manish.k@wings-marketing.in',
    phone: '+91 9230554212',
    mobileNumber: '9230554212',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Family Contact', relationship: 'Parent', phone: '+91 9230554200' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2024-07-24',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Manish Kumar',
      accountNumber: '923055421201',
      bankName: 'State Bank of India',
      ifscCode: 'SBIN0003412',
      panNumber: 'CDEFG3456H',
      branchName: 'Barasat, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-20',
    employeeCode: 'WC-020',
    firstName: 'Lakhsya',
    lastName: '',
    fullName: 'Lakhsya',
    avatarUrl: '',
    dateOfBirth: '1999-05-16',
    gender: 'Male',
    personalEmail: 'lakhsya@wings-marketing.in',
    workEmail: 'lakhsya@wings-marketing.in',
    phone: '+91 7003991358',
    mobileNumber: '7003991358',
    reportingTo: 'Sujal',
    companyRole: 'Executive',
    expiryDate: '21-10-2026',
    emergencyContact: { name: 'Family', relationship: 'Parent', phone: '+91 7003991300' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2023-10-21',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Lakhsya',
      accountNumber: '700399135801',
      bankName: 'HDFC Bank',
      ifscCode: 'HDFC0001890',
      panNumber: 'IJKLM7890N',
      branchName: 'Shyambazar, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-21',
    employeeCode: 'WC-021',
    firstName: 'Isha',
    lastName: 'Dutta',
    fullName: 'Isha Dutta',
    avatarUrl: '',
    dateOfBirth: '2000-11-20',
    gender: 'Female',
    personalEmail: 'isha.dutta@wings-marketing.in',
    workEmail: 'isha.dutta@wings-marketing.in',
    phone: '+91 9230189529',
    mobileNumber: '9230189529',
    reportingTo: 'Sujal',
    companyRole: 'Executive',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Family Contact', relationship: 'Mother', phone: '+91 9230189500' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2024-07-24',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Isha Dutta',
      accountNumber: '923018952901',
      bankName: 'ICICI Bank',
      ifscCode: 'ICIC0001456',
      panNumber: 'OPQRS1234T',
      branchName: 'Garia, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-22',
    employeeCode: 'WC-022',
    firstName: 'Himadri',
    lastName: 'Sarkar',
    fullName: 'HIMADRI SARKAR',
    avatarUrl: '',
    dateOfBirth: '1998-04-28',
    gender: 'Male',
    personalEmail: 'himadri.sarkar@wings-marketing.in',
    workEmail: 'himadri.sarkar@wings-marketing.in',
    phone: '+91 9230189533',
    mobileNumber: '9230189533',
    reportingTo: 'Sakshi Jaiswal',
    companyRole: 'Executive',
    expiryDate: '21-10-2026',
    emergencyContact: { name: 'Family', relationship: 'Brother', phone: '+91 9230189500' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2023-10-21',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Himadri Sarkar',
      accountNumber: '923018953301',
      bankName: 'Axis Bank',
      ifscCode: 'UTIB0003412',
      panNumber: 'UVWXY5678Z',
      branchName: 'Ballygunge, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-23',
    employeeCode: 'WC-023',
    firstName: 'Harshita',
    lastName: '',
    fullName: 'Harshita',
    avatarUrl: '',
    dateOfBirth: '1992-06-15',
    gender: 'Female',
    personalEmail: 'official.wingsmarketing@gmail.com',
    workEmail: 'official.wingsmarketing@gmail.com',
    phone: '+91 7044514241',
    mobileNumber: '7044514241',
    reportingTo: 'Board of Directors',
    companyRole: 'Org. Admin',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Executive Contact', relationship: 'Family', phone: '+91 7044514200' },
    currentAddress: 'Park Street, Kolkata, West Bengal',
    permanentAddress: 'Park Street, Kolkata, West Bengal',
    departmentId: 'dept-1',
    designation: 'HR Org Admin',
    joiningDate: '2023-01-01',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 15000,
      hra: 6000,
      allowances: 7000,
      incentives: 2000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Harshita',
      accountNumber: '704451424101',
      bankName: 'HDFC Bank',
      ifscCode: 'HDFC0000010',
      panNumber: 'ABCDE9999Z',
      branchName: 'Park Street Corporate, Kolkata'
    },
    documents: [
      { id: 'doc-emp23-1', title: 'Director Appointment Order', category: 'Employment', fileName: 'director_harshita_order.pdf', fileUrl: '#', uploadDate: '2023-01-01', verified: true }
    ]
  },
  {
    id: 'emp-24',
    employeeCode: 'WC-024',
    firstName: 'Debrup',
    lastName: 'Dutta',
    fullName: 'Debrup Dutta',
    avatarUrl: '',
    dateOfBirth: '1998-08-09',
    gender: 'Male',
    personalEmail: 'debrup.dutta@wings-marketing.in',
    workEmail: 'debrup.dutta@wings-marketing.in',
    phone: '+91 9230195316',
    mobileNumber: '9230195316',
    reportingTo: 'Sujal',
    companyRole: 'Executive',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Family', relationship: 'Parent', phone: '+91 9230195300' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2024-07-24',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Debrup Dutta',
      accountNumber: '923019531601',
      bankName: 'State Bank of India',
      ifscCode: 'SBIN0001567',
      panNumber: 'FGHIJ9012K',
      branchName: 'Lake Gardens, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-25',
    employeeCode: 'WC-025',
    firstName: 'Debraj',
    lastName: 'Ghosh',
    fullName: 'Debraj Ghosh',
    avatarUrl: '',
    dateOfBirth: '1999-03-24',
    gender: 'Male',
    personalEmail: 'debraj.ghosh@wings-marketing.in',
    workEmail: 'debraj.ghosh@wings-marketing.in',
    phone: '+91 7439058973',
    mobileNumber: '7439058973',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Family Contact', relationship: 'Parent', phone: '+91 7439058900' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2024-07-24',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Debraj Ghosh',
      accountNumber: '743905897301',
      bankName: 'HDFC Bank',
      ifscCode: 'HDFC0001945',
      panNumber: 'KLMNO3456P',
      branchName: 'Howrah Station, Howrah'
    },
    documents: []
  },
  {
    id: 'emp-26',
    employeeCode: 'WC-026',
    firstName: 'Debarun',
    lastName: '',
    fullName: 'Debarun',
    avatarUrl: '',
    dateOfBirth: '1996-01-19',
    gender: 'Male',
    personalEmail: 'debarun@wings-marketing.in',
    workEmail: 'debarun@wings-marketing.in',
    phone: '+91 9230965191',
    mobileNumber: '9230965191',
    reportingTo: 'Ardhendu',
    companyRole: 'Manager',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Family', relationship: 'Parent', phone: '+91 9230965100' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Manager',
    joiningDate: '2024-07-24',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 15000,
      hra: 6000,
      allowances: 7000,
      incentives: 2000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Debarun',
      accountNumber: '923096519101',
      bankName: 'ICICI Bank',
      ifscCode: 'ICIC0002134',
      panNumber: 'QRSTU7890V',
      branchName: 'Rashbehari, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-27',
    employeeCode: 'WC-027',
    firstName: 'Chirag',
    lastName: 'Baheti',
    fullName: 'Chirag Baheti',
    avatarUrl: '',
    dateOfBirth: '1998-07-11',
    gender: 'Male',
    personalEmail: 'chirag.baheti@wings-marketing.in',
    workEmail: 'chirag.baheti@wings-marketing.in',
    phone: '+91 9230554213',
    mobileNumber: '9230554213',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '21-10-2026',
    emergencyContact: { name: 'Family', relationship: 'Parent', phone: '+91 9230554200' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2023-10-21',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Chirag Baheti',
      accountNumber: '923055421301',
      bankName: 'Axis Bank',
      ifscCode: 'UTIB0001945',
      panNumber: 'WXYZA1234B',
      branchName: 'Burrabazar, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-28',
    employeeCode: 'WC-028',
    firstName: 'Bhubaneswar',
    lastName: 'Chakraborty',
    fullName: 'Bhubaneswar Chakraborty',
    avatarUrl: '',
    dateOfBirth: '1997-10-02',
    gender: 'Male',
    personalEmail: 'bhubaneswar.c@wings-marketing.in',
    workEmail: 'bhubaneswar.c@wings-marketing.in',
    phone: '+91 9230521845',
    mobileNumber: '9230521845',
    reportingTo: 'Sakshi Jaiswal',
    companyRole: 'Executive',
    expiryDate: '21-10-2026',
    emergencyContact: { name: 'Family', relationship: 'Father', phone: '+91 9230521800' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2023-10-21',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Bhubaneswar Chakraborty',
      accountNumber: '923052184501',
      bankName: 'Kotak Mahindra Bank',
      ifscCode: 'KKBK0002345',
      panNumber: 'CDEFG5678H',
      branchName: 'Kasba, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-29',
    employeeCode: 'WC-029',
    firstName: 'Avirup',
    lastName: '',
    fullName: 'Avirup',
    avatarUrl: '',
    dateOfBirth: '1998-05-30',
    gender: 'Male',
    personalEmail: 'avirup@wings-marketing.in',
    workEmail: 'avirup@wings-marketing.in',
    phone: '+91 9230628050',
    mobileNumber: '9230628050',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Family', relationship: 'Parent', phone: '+91 9230628000' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2024-07-24',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Avirup',
      accountNumber: '923062805001',
      bankName: 'State Bank of India',
      ifscCode: 'SBIN0001890',
      panNumber: 'IJKLM9012N',
      branchName: 'Ultadanga, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-30',
    employeeCode: 'WC-030',
    firstName: 'Arman',
    lastName: '',
    fullName: 'Arman',
    avatarUrl: '',
    dateOfBirth: '1999-08-14',
    gender: 'Male',
    personalEmail: 'arman@wings-marketing.in',
    workEmail: 'arman@wings-marketing.in',
    phone: '+91 9230346015',
    mobileNumber: '9230346015',
    reportingTo: 'Harshita',
    companyRole: 'Executive',
    expiryDate: '21-10-2026',
    emergencyContact: { name: 'Family', relationship: 'Parent', phone: '+91 9230346000' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2023-10-21',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Arman',
      accountNumber: '923034601501',
      bankName: 'HDFC Bank',
      ifscCode: 'HDFC0001456',
      panNumber: 'OPQRS3456T',
      branchName: 'Entally, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-31',
    employeeCode: 'WC-031',
    firstName: 'Arghadeep',
    lastName: '',
    fullName: 'Arghadeep',
    avatarUrl: '',
    dateOfBirth: '1998-11-23',
    gender: 'Male',
    personalEmail: 'arghadeep@wings-marketing.in',
    workEmail: 'arghadeep@wings-marketing.in',
    phone: '+91 9230521847',
    mobileNumber: '9230521847',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '21-10-2026',
    emergencyContact: { name: 'Family', relationship: 'Parent', phone: '+91 9230521800' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2023-10-21',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Arghadeep',
      accountNumber: '923052184701',
      bankName: 'ICICI Bank',
      ifscCode: 'ICIC0001980',
      panNumber: 'UVWXY7890Z',
      branchName: 'Madhyamgram, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-32',
    employeeCode: 'WC-032',
    firstName: 'Ardhendu',
    lastName: '',
    fullName: 'Ardhendu',
    avatarUrl: '',
    dateOfBirth: '1990-12-05',
    gender: 'Male',
    personalEmail: 'retail@wings-marketing.in',
    workEmail: 'retail@wings-marketing.in',
    phone: '+91 9230554211',
    mobileNumber: '9230554211',
    reportingTo: 'Board of Directors',
    companyRole: 'Org. Admin',
    expiryDate: '21-10-2026',
    emergencyContact: { name: 'Corporate Contact', relationship: 'Family', phone: '+91 9230554200' },
    currentAddress: 'Ballygunge Circular Road, Kolkata, West Bengal',
    permanentAddress: 'Ballygunge Circular Road, Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Org Admin',
    joiningDate: '2023-01-01',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 15000,
      hra: 6000,
      allowances: 7000,
      incentives: 2000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Ardhendu',
      accountNumber: '923055421101',
      bankName: 'Axis Bank',
      ifscCode: 'UTIB0000050',
      panNumber: 'FGHIJ9999K',
      branchName: 'Ballygunge Main, Kolkata'
    },
    documents: [
      { id: 'doc-emp32-1', title: 'Director Appointment Order', category: 'Employment', fileName: 'head_of_sales_appointment.pdf', fileUrl: '#', uploadDate: '2023-01-01', verified: true }
    ]
  },
  {
    id: 'emp-33',
    employeeCode: 'WC-033',
    firstName: 'Aniruddha',
    lastName: 'Paul',
    fullName: 'Aniruddha Paul',
    avatarUrl: '',
    dateOfBirth: '1998-09-08',
    gender: 'Male',
    personalEmail: 'aniruddha.paul@wings-marketing.in',
    workEmail: 'aniruddha.paul@wings-marketing.in',
    phone: '+91 9230651445',
    mobileNumber: '9230651445',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Family', relationship: 'Parent', phone: '+91 9230651400' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2024-07-24',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Aniruddha Paul',
      accountNumber: '923065144501',
      bankName: 'HDFC Bank',
      ifscCode: 'HDFC0002134',
      panNumber: 'KLMNO7890P',
      branchName: 'Gariahat, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-34',
    employeeCode: 'WC-034',
    firstName: 'Aniket',
    lastName: '',
    fullName: 'Aniket',
    avatarUrl: '',
    dateOfBirth: '1999-02-18',
    gender: 'Male',
    personalEmail: 'aniket@wings-marketing.in',
    workEmail: 'aniket@wings-marketing.in',
    phone: '+91 9230965188',
    mobileNumber: '9230965188',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '21-10-2026',
    emergencyContact: { name: 'Family', relationship: 'Parent', phone: '+91 9230965100' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2023-10-21',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Aniket',
      accountNumber: '923096518801',
      bankName: 'ICICI Bank',
      ifscCode: 'ICIC0003412',
      panNumber: 'QRSTU1234V',
      branchName: 'Behala, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-35',
    employeeCode: 'WC-035',
    firstName: 'Akash',
    lastName: '',
    fullName: 'Akash',
    avatarUrl: '',
    dateOfBirth: '1998-06-11',
    gender: 'Male',
    personalEmail: 'akash@wings-marketing.in',
    workEmail: 'akash@wings-marketing.in',
    phone: '+91 9230621915',
    mobileNumber: '9230621915',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '21-10-2026',
    emergencyContact: { name: 'Family', relationship: 'Parent', phone: '+91 9230621900' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2023-10-21',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Akash',
      accountNumber: '923062191501',
      bankName: 'State Bank of India',
      ifscCode: 'SBIN0000456',
      panNumber: 'WXYZA5678B',
      branchName: 'Salt Lake, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-36',
    employeeCode: 'WC-036',
    firstName: 'Aishi',
    lastName: 'Mukherjee',
    fullName: 'Aishi Mukherjee',
    avatarUrl: '',
    dateOfBirth: '2000-03-17',
    gender: 'Female',
    personalEmail: 'aishi.mukherjee@wings-marketing.in',
    workEmail: 'aishi.mukherjee@wings-marketing.in',
    phone: '+91 9230521852',
    mobileNumber: '9230521852',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Family Contact', relationship: 'Mother', phone: '+91 9230521800' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2024-07-24',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Aishi Mukherjee',
      accountNumber: '923052185201',
      bankName: 'Kotak Mahindra Bank',
      ifscCode: 'KKBK0001945',
      panNumber: 'CDEFG9012H',
      branchName: 'Rajarhat, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-37',
    employeeCode: 'WC-037',
    firstName: 'Aditya',
    lastName: 'Gupta',
    fullName: 'Aditya Gupta',
    avatarUrl: '',
    dateOfBirth: '1998-10-29',
    gender: 'Male',
    personalEmail: 'aditya.gupta@wings-marketing.in',
    workEmail: 'aditya.gupta@wings-marketing.in',
    phone: '+91 7003959406',
    mobileNumber: '7003959406',
    reportingTo: 'Sujal',
    companyRole: 'Executive',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Family', relationship: 'Father', phone: '+91 7003959400' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2024-07-24',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Aditya Gupta',
      accountNumber: '700395940601',
      bankName: 'HDFC Bank',
      ifscCode: 'HDFC0001456',
      panNumber: 'IJKLM3456N',
      branchName: 'Bhowanipore, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-38',
    employeeCode: 'WC-038',
    firstName: 'Abhigyan',
    lastName: '',
    fullName: 'Abhigyan',
    avatarUrl: '',
    dateOfBirth: '1999-07-07',
    gender: 'Male',
    personalEmail: 'abhigyan@wings-marketing.in',
    workEmail: 'abhigyan@wings-marketing.in',
    phone: '+91 9230195319',
    mobileNumber: '9230195319',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '21-10-2026',
    emergencyContact: { name: 'Family', relationship: 'Parent', phone: '+91 9230195300' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2023-10-21',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Abhigyan',
      accountNumber: '923019531901',
      bankName: 'Axis Bank',
      ifscCode: 'UTIB0001890',
      panNumber: 'OPQRS7890T',
      branchName: 'Salt Lake Sector 1, Kolkata'
    },
    documents: []
  },
  {
    id: 'emp-39',
    employeeCode: 'WC-039',
    firstName: 'Aakash',
    lastName: 'Trivedi',
    fullName: 'Aakash Trivedi',
    avatarUrl: '',
    dateOfBirth: '1998-01-14',
    gender: 'Male',
    personalEmail: 'aakash.trivedi@wings-marketing.in',
    workEmail: 'aakash.trivedi@wings-marketing.in',
    phone: '+91 9230195323',
    mobileNumber: '9230195323',
    reportingTo: 'Ardhendu',
    companyRole: 'Executive',
    expiryDate: '24-07-2027',
    emergencyContact: { name: 'Family Contact', relationship: 'Parent', phone: '+91 9230195300' },
    currentAddress: 'Kolkata, West Bengal',
    permanentAddress: 'Kolkata, West Bengal',
    departmentId: 'dept-2',
    designation: 'Sales Executive',
    joiningDate: '2024-07-24',
    employmentType: 'Full Time',
    workLocation: 'Headquarters (Kolkata/Mumbai)',
    probationPeriodMonths: 0,
    status: 'Active',
    salary: {
      basic: 10000,
      hra: 4000,
      allowances: 5000,
      incentives: 1000,
      bonus: 0,
      pf: 1800,
      esi: 0,
      professionalTax: 200,
      tds: 0,
      otherDeductions: 0
    },
    bankDetails: {
      accountHolderName: 'Aakash Trivedi',
      accountNumber: '923019532301',
      bankName: 'HDFC Bank',
      ifscCode: 'HDFC0000456',
      panNumber: 'UVWXY1234Z',
      branchName: 'Ballygunge, Kolkata'
    },
    documents: []
  }
];

// Leave balances for team members
export const initialLeaveBalances: Record<string, LeaveBalance> = {
  default: {
    casual: { allocated: 12, used: 2 },
    sick: { allocated: 10, used: 1 },
    paid: { allocated: 18, used: 3 },
    wfh: { allocated: 24, used: 4 },
  },
  'emp-23': {
    casual: { allocated: 14, used: 1 },
    sick: { allocated: 10, used: 0 },
    paid: { allocated: 21, used: 2 },
    wfh: { allocated: 30, used: 5 },
  },
  'emp-32': {
    casual: { allocated: 14, used: 2 },
    sick: { allocated: 10, used: 0 },
    paid: { allocated: 21, used: 1 },
    wfh: { allocated: 30, used: 4 },
  },
  'emp-11': {
    casual: { allocated: 12, used: 3 },
    sick: { allocated: 10, used: 2 },
    paid: { allocated: 18, used: 4 },
    wfh: { allocated: 24, used: 6 },
  }
};

export const initialLeaveRequests: LeaveRequest[] = [
  {
    id: 'leave-1',
    employeeId: 'emp-4', // Subhasish Bose
    leaveType: 'Paid Leave',
    startDate: '2026-10-05',
    endDate: '2026-10-07',
    isHalfDay: false,
    totalDays: 3,
    reason: 'Family festival celebration and travel.',
    attachmentName: 'festival_leave.pdf',
    status: 'Pending',
    createdAt: '2026-09-27'
  },
  {
    id: 'leave-2',
    employeeId: 'emp-11', // Sakshi Jaiswal
    leaveType: 'Work From Home',
    startDate: '2026-09-30',
    endDate: '2026-10-01',
    isHalfDay: false,
    totalDays: 2,
    reason: 'Quarterly enterprise sales closure and contract draft sprint.',
    status: 'Approved',
    reviewedBy: 'Harshita',
    reviewerComment: 'Approved. Ensure corporate client contracts are executed.',
    createdAt: '2026-09-25'
  },
  {
    id: 'leave-3',
    employeeId: 'emp-2', // Tamaghna
    leaveType: 'Sick Leave',
    startDate: '2026-09-28',
    endDate: '2026-09-28',
    isHalfDay: true,
    halfDayPeriod: 'second_half',
    totalDays: 0.5,
    reason: 'Medical checkup appointment.',
    status: 'Pending',
    createdAt: '2026-09-28'
  }
];

// Attendance records for Today for all 39 team members (11:00 AM - 08:00 PM shift)
export const initialAttendanceRecords: AttendanceRecord[] = initialEmployees.map((emp, idx) => {
  const isPresent = idx !== 8 && idx !== 17;
  const isLate = idx === 5 || idx === 11 || idx === 20;
  const isAbsent = idx === 8;
  const isWFH = idx === 10 || idx === 2;

  let checkIn = '10:50';
  let checkOut = '20:05';
  let status: any = 'Present';
  let hours = 9.1;

  if (isLate) {
    checkIn = '11:25';
    checkOut = '20:10';
    status = 'Late';
    hours = 8.7;
  } else if (isWFH) {
    checkIn = '11:00';
    checkOut = '20:00';
    status = 'Work From Home';
    hours = 9.0;
  } else if (isAbsent) {
    checkIn = undefined as any;
    checkOut = undefined as any;
    status = 'Absent';
    hours = 0;
  }

  return {
    id: `att-today-${emp.id}`,
    employeeId: emp.id,
    date: '2026-09-28',
    checkIn,
    checkOut,
    workingHours: hours,
    breakMinutes: 45,
    overtimeHours: hours > 9 ? Number((hours - 9).toFixed(1)) : 0,
    status
  };
});

// Tasks strictly oriented towards Sales & HR workflows
export const initialTasks: TaskItem[] = [
  {
    id: 'task-1',
    title: 'Execute Q4 Corporate & Enterprise Sales Campaign',
    description: 'Onboard 15 new enterprise retail brands, execute merchant partnership agreements, and coordinate client presentations.',
    assignedToId: 'emp-11', // Sakshi Jaiswal
    createdById: 'emp-23', // Harshita
    clientName: 'Wings Enterprise Accounts',
    projectName: 'Q4 Enterprise Blitz',
    departmentId: 'dept-2',
    priority: 'Urgent',
    startDate: '2026-09-22',
    deadline: '2026-10-06',
    status: 'In Progress',
    comments: [
      { id: 'tc-1', taskId: 'task-1', authorId: 'emp-23', authorName: 'Harshita', text: 'Client commercial agreements for Q4 have been reviewed and approved.', createdAt: '2026-09-23 11:30' },
      { id: 'tc-2', taskId: 'task-1', authorId: 'emp-11', authorName: 'Sakshi Jaiswal', text: 'First 6 enterprise retail accounts signed; targeting remainder by next week.', createdAt: '2026-09-26 15:40' }
    ],
    createdAt: '2026-09-22',
    updatedAt: '2026-09-26'
  },
  {
    id: 'task-2',
    title: 'Audit Biometric Punch & Attendance Regularization Log',
    description: 'Reconcile biometric logs with manual punch correction requests for all 39 staff members before monthly payroll freeze.',
    assignedToId: 'emp-1', // Varsha
    createdById: 'emp-23', // Harshita
    clientName: 'Wings Corporate HR',
    projectName: 'Monthly HR Audit & Compliance',
    departmentId: 'dept-1',
    priority: 'High',
    startDate: '2026-09-20',
    deadline: '2026-10-02',
    status: 'In Review',
    comments: [
      { id: 'tc-3', taskId: 'task-2', authorId: 'emp-1', authorName: 'Varsha', text: 'Attendance logs synchronized and verified across all executive accounts.', createdAt: '2026-09-27 16:10' }
    ],
    createdAt: '2026-09-20',
    updatedAt: '2026-09-27'
  },
  {
    id: 'task-3',
    title: 'Retail Merchant Network Expansion Outreach',
    description: 'Distribute updated retail pricing matrices, coordinate lead call lists with regional teams, and track conversion rates.',
    assignedToId: 'emp-12', // Ronodip Sill
    createdById: 'emp-32', // Ardhendu
    clientName: 'Wings Retail Network',
    projectName: 'Retail Merchant Outreach',
    departmentId: 'dept-2',
    priority: 'High',
    startDate: '2026-09-25',
    deadline: '2026-10-05',
    status: 'In Progress',
    comments: [],
    createdAt: '2026-09-25',
    updatedAt: '2026-09-25'
  },
  {
    id: 'task-4',
    title: 'New Sales Executive Onboarding & Training Plan',
    description: 'Prepare documentation packs, sales pitch scripts, CRM portal logins, and KPI scorecards for incoming executives.',
    assignedToId: 'emp-16', // Priyam Dhar
    createdById: 'emp-23', // Harshita
    clientName: 'Wings Talent Acquisition',
    projectName: 'Sales Onboarding Excellence',
    departmentId: 'dept-1',
    priority: 'Medium',
    startDate: '2026-09-24',
    deadline: '2026-10-03',
    status: 'To Do',
    comments: [],
    createdAt: '2026-09-24',
    updatedAt: '2026-09-24'
  }
];

// Performance Reviews strictly for Sales & HR leaders
export const initialPerformanceReviews: PerformanceReview[] = [
  {
    id: 'rev-1',
    employeeId: 'emp-11', // Sakshi Jaiswal
    reviewerId: 'emp-23', // Harshita
    reviewPeriod: 'Q2 2026',
    qualityOfWork: 5,
    productivity: 5,
    communication: 5,
    teamwork: 5,
    punctuality: 5,
    responsibility: 5,
    finalRating: 5.0,
    managerComments: 'Sakshi continues to deliver exceptional leadership in closing high-value corporate client accounts and mentoring her sales pod.',
    employeeComments: 'Pleased with team performance and geared up for ambitious Q3/Q4 festive sales targets.',
    status: 'Completed',
    createdAt: '2026-07-05',
    updatedAt: '2026-07-08'
  },
  {
    id: 'rev-2',
    employeeId: 'emp-1', // Varsha
    reviewerId: 'emp-23', // Harshita
    reviewPeriod: 'Q2 2026',
    qualityOfWork: 5,
    productivity: 5,
    communication: 5,
    teamwork: 5,
    punctuality: 5,
    responsibility: 5,
    finalRating: 5.0,
    managerComments: 'Varsha has maintained flawless HR operations, zero compliance lapses, and prompt resolution of attendance corrections.',
    employeeComments: 'Committed to automating leave reconciliation and enhancing employee experience.',
    status: 'Completed',
    createdAt: '2026-07-02',
    updatedAt: '2026-07-04'
  }
];

// Initial payroll records for all 39 team members
export const initialPayrollRecords: PayrollRecord[] = initialEmployees.map(emp => {
  const sal = emp.salary;
  const gross = sal.basic + sal.hra + sal.allowances + sal.incentives + sal.bonus;
  const totalDeductions = sal.pf + sal.esi + sal.professionalTax + sal.tds + sal.otherDeductions;
  const net = Math.max(0, gross - totalDeductions);

  return {
    id: `pay-2026-09-${emp.id}`,
    monthYear: '2026-09',
    employeeId: emp.id,
    basicSalary: sal.basic,
    hra: sal.hra,
    allowances: sal.allowances,
    incentives: sal.incentives,
    bonus: sal.bonus,
    overtime: 0,
    grossSalary: gross,
    lateDeduction: 0,
    leaveWithoutPay: 0,
    pf: sal.pf,
    esi: sal.esi,
    professionalTax: sal.professionalTax,
    tds: sal.tds,
    advance: 0,
    otherDeduction: sal.otherDeductions,
    totalDeductions,
    netSalary: net,
    status: 'Approved',
    generatedDate: '2026-09-28',
    disbursedDate: '2026-09-30'
  };
});

export const initialDocuments: DocumentItem[] = [
  {
    id: 'doc-1',
    title: 'Wings Corporation Employee Handbook & HR Policy 2026',
    category: 'Company Policy',
    fileName: 'Wings_Employee_Handbook_2026.pdf',
    fileUrl: '#',
    fileSize: '3.4 MB',
    fileType: 'application/pdf',
    uploadDate: '2026-01-15',
    uploadedById: 'emp-23',
    uploadedByName: 'Harshita (Org. Admin)',
    isCompanyWide: true,
    requiresAcknowledgement: true,
    status: 'Active'
  },
  {
    id: 'doc-2',
    title: 'Corporate Sales Incentive & Commission Structure 2026-27',
    category: 'Salary',
    fileName: 'Sales_Commission_Structure_2026.pdf',
    fileUrl: '#',
    fileSize: '1.2 MB',
    fileType: 'application/pdf',
    uploadDate: '2026-04-01',
    uploadedById: 'emp-32',
    uploadedByName: 'Ardhendu (Head of Sales)',
    isCompanyWide: true,
    requiresAcknowledgement: true,
    status: 'Active'
  },
  {
    id: 'doc-3',
    title: 'Standard Sales Pitch Deck & Merchant Agreement Draft',
    category: 'Employment',
    fileName: 'Merchant_Agreement_Template.docx',
    fileUrl: '#',
    fileSize: '820 KB',
    fileType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    uploadDate: '2026-07-24',
    uploadedById: 'emp-11',
    uploadedByName: 'Sakshi Jaiswal (Manager)',
    isCompanyWide: true,
    requiresAcknowledgement: false,
    status: 'Active'
  }
];

export const initialHolidays: Holiday[] = [
  { id: 'hol-1', name: 'Gandhi Jayanti', date: '2026-10-02', type: 'National Holiday', description: 'National celebration honoring Mahatma Gandhi' },
  { id: 'hol-2', name: 'Maha Saptami (Durga Puja)', date: '2026-10-18', type: 'Company Holiday', description: 'Auspicious Durga Puja festival celebration' },
  { id: 'hol-3', name: 'Vijaya Dashami (Dussehra)', date: '2026-10-21', type: 'National Holiday', description: 'Grand celebration of victory of good over evil' },
  { id: 'hol-4', name: 'Diwali (Kali Puja)', date: '2026-11-08', type: 'National Holiday', description: 'Grand festival of lights and company celebration' },
  { id: 'hol-5', name: 'Guru Nanak Jayanti', date: '2026-11-24', type: 'National Holiday', description: 'Birth anniversary of Guru Nanak Dev Ji' },
  { id: 'hol-6', name: 'Christmas Day', date: '2026-12-25', type: 'National Holiday', description: 'Winter holiday celebration' }
];

export const initialAnnouncements: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Wings Corporation Festive Sales Targets & Operations Sync',
    description: 'Welcome to the festive quarter! All retail and enterprise sales outreach, merchant partnerships, and client campaigns are live. Reach out to Harshita (HR) or Ardhendu (Sales) for any operational enablement.',
    audience: 'Everyone',
    publishDate: '2026-09-28',
    expiryDate: '2026-10-15',
    priority: 'important',
    createdById: 'emp-23',
    createdByName: 'Harshita (Org. Admin)',
    createdAt: '2026-09-28 09:30'
  },
  {
    id: 'ann-2',
    title: 'September 2026 Salary Disbursal Schedule',
    description: 'September 2026 payroll has been validated and approved for all 39 staff members across Sales and HR. Direct bank credits will be completed on September 30, 2026.',
    audience: 'Everyone',
    publishDate: '2026-09-28',
    expiryDate: '2026-10-05',
    priority: 'normal',
    createdById: 'emp-23',
    createdByName: 'Harshita (Org. Admin)',
    createdAt: '2026-09-28 11:00'
  }
];

export const initialNotifications: NotificationItem[] = [
  { id: 'notif-1', title: 'Workforce Roster Synchronized', message: 'All 39 official Wings Corporation Sales & HR team members have been registered.', type: 'announcement', isRead: false, linkUrl: 'employees', createdAt: '2026-09-28 09:00' },
  { id: 'notif-2', title: 'September Payroll Approved', message: 'September 2026 payroll approved for all 39 team members.', type: 'payroll', isRead: false, linkUrl: 'payroll', createdAt: '2026-09-28 10:15' }
];

export const initialAuditLogs: AuditLog[] = [
  { id: 'aud-1', performedById: 'emp-23', performedByName: 'Harshita', performedByRole: 'super_admin', action: 'Roster Synchronized (Sales & HR)', details: 'Configured official 39-member roster with mobile numbers, reporting lines, and validity dates with zero external photo avatars.', ipAddress: '192.168.1.10', timestamp: '2026-09-28 09:00:15' },
  { id: 'aud-2', performedById: 'emp-32', performedByName: 'Ardhendu', performedByRole: 'super_admin', action: 'Sales & HR Payroll Validated', details: 'Approved salary statements for 39 staff members.', ipAddress: '192.168.1.12', timestamp: '2026-09-28 10:15:30' }
];

export const initialCompanySettings: CompanySettings = {
  companyName: 'Wings Corporation',
  tagline: 'Manage your workforce. Simplify your workplace.',
  logoUrl: '',
  address: 'Wings Corporation HQ, Senapati Bapat Marg, Mumbai / Park Street, Kolkata, India',
  email: 'official.wingsmarketing@gmail.com',
  phone: '+91 7044514241',
  officeStartTime: '11:00',
  officeEndTime: '20:00',
  gracePeriodMinutes: 15,
  workingHoursPerDay: 9,
  minFullDayHours: 8,
  minHalfDayHours: 4,
  weeklyOffDays: ['Sunday'],
  financialYear: '2026-2027',
  currencySymbol: '₹'
};
